### ISSUE TITLE
About automatically detected Windows boot entries, not boot entries added by yourself., how to customize icons.

### ISSUE THREAD

**Issue by w19996** [blackosx/OpenCanopyIcons#4]
"For an automatically discovered entry it is read from the .contentFlavour file next to the bootloader,if present."
I can't understand the meaning of this sentence, what is. contentFlavour, and where should this file be placed?Could you use a picture to show it? Thank you.

**Comment by a-n-t-i-b-a-r-y-o-n** [comment]
@w19996 - This quote appears to be from the OpenCore configuration guide, which is separate from this project.

This is a repo for icons, not OpenCore itself.
You may try opening an issue on the OpenCore repo instead:

https://github.com/acidanthera/OpenCorePkg

Alternatively, this post on InsanelyMac from around the same time this issue was opened may solve your issue:

https://www.insanelymac.com/forum/topic/348853-hello-everyone-what-should-i-do-about-customizing-icons-of-different-versions-of-windows/

If you've found a solution (or that InsanelyMac forum post was yours) would you mind closing this issue?

Hope this helps! 👍

**Comment by blackosx** [comment]
@w19996 I hope you've managed to resolve your query but if not, .contentFlavour is the name of a text file you create with content such as **Windows11:Windows**
and place next to your boot loader, for example EFI/Microsoft/Boot/.contentFlavour  
OpenCanopy will then look for an icon named Windows11.icns in the theme dir, if not found then it will look for Windows.icns.

Thanks for commenting @g-r-a-v-i-t-y-w-a-v-e

Closing.

**Comment by long2ice** [comment]
What about ubuntu? Which can't detect automatically
